### ISSUE TITLE
Can this work for Godot 4+ games with multiplayer and open world chunks?

### ISSUE THREAD

**Issue by WithinAmnesia** [SlashScreen/skelerealms#14]
Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET.

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback.

**Comment by SlashScreen** [comment]
It looks like you're making an ARPG, which this framework is not designed for.

**Comment by WithinAmnesia** [comment]
Here is an update since I last posted.
https://jonathaneeckhout.itch.io/jdungeon For the goal right now it is easy to play this but imagine it has seamless chunk loading and unloading. As instead of the black world boundary a new chunk loads in seamlessly. What are your suggestions and thoughts?

Update: https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

My initial testing seems to feel even faster combat with the 128x128 chunk. This 128x128 chunk has the same amount of entities as the 256x256 chunk. For I moved all of the entities over into the 128x128 chunk. This 128x128 chunk is a good test for using the Infinite-Worlds using the BinarySerializer for Godot 4.2+ from Theraot: https://gist.github.com/theraot/31515e28e2d8bfea33f6c6d5bcd852f6 . There needs to be some testing how to make the chunks seamlessly load and unload.

**Comment by WithinAmnesia** [comment]
> It looks like you're making an ARPG, which this framework is not designed for.

Oh hey how are you? I asked you twice lol. thanks for replying twice too lol. https://github.com/SlashScreen/chunx/issues/2

Can you help with the chunks like you seem really skilled and like anything helps the this big community wide puzzle and once its solved it is the key to massive multiplayer games built by the community forever free. Any thing helps like here is teh test chunk if you feel interested in testing it https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

Also here is Theraot's code if you are curious about this and like anything for solutions or ideas or leads or what to do next is super important. For this will probably take a community of open minded people to solve. The more the merrier.

Please if you feel like you think you know a lead or possible way to solve this big community wide puzzle please feel free to ask questions and give suggestions and I really hope to finnd solutions with you and the open minded community on this critical Godot multiplayer chunk infrastructure puzzle. What do to? Any feedback is welcome.
